### ISSUE TITLE
Refactoring get tokens in if-blocks

### ISSUE THREAD

**Issue by poetiner** [nn-students-2021h2/Team_6#17]
Утвердить как мы пишем: if (tokens["negative"] == False)
И в дальнейшем писать одним стилем
А лучше: if tokens["some_token"] :
Без ==
Без ()

**Comment by TrampI550** [comment]
Будем писать так, хорошо

**Comment by TrampI550** [comment]
Fixed

**Comment by TrampI550** [comment]
Fixed
