### ISSUE TITLE
user_images_dir Bug

### ISSUE THREAD

**Issue by poetiner** [nn-students-2021h2/Team_6#21]
Либо:
1. Заменить user_images_dir(глобальную переменную) на функцию.
2. Передавать user_images_dir через состояния

**Comment by TrampI550** [comment]
Насчёт 2-ого способа не могу найти информации, пока сделаю через 1-ый.

**Comment by TrampI550** [comment]
Сделал через 1-ый способ. Подожду информации по поводу 2-го.

**Comment by TrampI550** [comment]
Оставляем так
