### ISSUE TITLE
Убрать глобальные tokens

### ISSUE THREAD

**Issue by poetiner** [nn-students-2021h2/Team_6#22]
Убрать глобальные tokens и использовать либо поиск в папке файла пользователя, либо json содержащий состояние пользователя, либо используя передачу состояний между функциями aiogram

**Comment by TrampI550** [comment]
Если передача данных через состояния действительно существует, то сделаем ее

**Comment by TrampI550** [comment]
Tokens удалены
Осталось:
~~~
Разобраться с флагом (tokens['flag']) из гамма фильтра

Разобраться с удалением изображений после завершения работы
~~~

**Comment by poetiner** [comment]
https://docs.aiogram.dev/en/latest/dispatcher/fsm.html#storage

**Comment by TrampI550** [comment]
Добавил пару доп. состояний в машину состояний, они хорошо заменяют токены
